language: node_js
node_js:
    - "8"

script:
    - wget https://broth.itch.ovh/butler/linux-amd64/LATEST/.zip -O butler.zip --progress=dot
    - unzip butler.zip
    - chmod +x butler
    - export PATH="$PATH:$PWD"
    - butler -V
    - export DEBUG="butlerd:*"
    - npm run precompile
    - npm run node-test
